$(document).ready(function(){
  $("#ti1").hide();
  $("#t1").mouseover(function(){
      $("#ti1").show();
  })
  $("#t1").mouseleave(function(){
      $("#ti1").hide();
  })
})
$(document).ready(function(){
  $("#ti2").hide();
  $("#t2").mouseover(function(){
      $("#ti2").show();
  })
  $("#t2").mouseleave(function(){
      $("#ti2").hide();
  })
})
$(document).ready(function(){
  $("#ti3").hide();
  $("#t3").mouseover(function(){
      $("#ti3").show();
  })
  $("#t3").mouseleave(function(){
      $("#ti3").hide();
  })
})
$(document).ready(function(){
  $("#ti4").hide();
  $("#t4").mouseover(function(){
      $("#ti4").show();
  })
  $("#t4").mouseleave(function(){
      $("#ti4").hide();
  })
})
$(document).ready(function(){
  $("#ti5").hide();
  $("#t5").mouseover(function(){
      $("#ti5").show();
  })
  $("#t5").mouseleave(function(){
      $("#ti5").hide();
  })
})
$(document).ready(function(){
  $("#ti6").hide();
  $("#t6").mouseover(function(){
      $("#ti6").show();
  })
  $("#t6").mouseleave(function(){
      $("#ti6").hide();
  })
})
$(document).ready(function(){
  $("#ti7").hide();
  $("#t7").mouseover(function(){
      $("#ti7").show();
  })
  $("#t7").mouseleave(function(){
      $("#ti7").hide();
  })
})
$(document).ready(function(){
  $("#ti8").hide();
  $("#t8").mouseover(function(){
      $("#ti8").show();
  })
  $("#t8").mouseleave(function(){
      $("#ti8").hide();
  })
})
$(document).ready(function(){
  $("#ti9").hide();
  $("#t9").mouseover(function(){
      $("#ti9").show();
  })
  $("#t9").mouseleave(function(){
      $("#ti9").hide();
  })
})
